apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
        - name: ${SERVICE}
          image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          ports:
            - containerPort: 80
            - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${SERVICE}
  name: ${SERVICE}
spec:
  ports:
    - name: demo-multitech-vue
      nodePort: 33080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ${SERVICE}
  type: NodePort
