version: '3'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    deploy:
      replicas: 2
    networks:
      dev-demo-network:
        aliases:
          - demo-go

networks:
  dev-demo-network:
    external: true
