version: '3'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    deploy:
      replicas: 2
    networks:
      staging-demo-network:
        aliases:
          - demo-python

networks:
  staging-demo-network:
    external: true
