version: '3'

services:
  grafana:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - '8013:3000'
    networks:
      monitoring-network:
        aliases:
          - prometheus-grafana

networks:
  monitoring-network:
    external: true
