version: '3'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    deploy:
      replicas: 2
    networks:
      staging-demo-multitech-network:
        aliases:
          - demo-multitech-go

networks:
  staging-demo-multitech-network:
    external: true
