apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  service: ${SERVICE}
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: ${SERVICE}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${SERVICE}-${SERVICE_VERSION}
  labels:
    app: ${SERVICE}
    version: ${SERVICE_VERSION}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${SERVICE}
        version: ${SERVICE_VERSION}
    spec:
      containers:
        - name: ${SERVICE}
          image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          ports:
            - containerPort: 80
