version: '3'

services:
  prometheus:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - '8012:9090'
    networks:
      monitoring-network:
        aliases:
          - prometheus

networks:
  monitoring-network:
    external: true
