version: "3"

services:
  elk-kibana:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - "8011:5601"
    networks:
      elk-network:
        aliases:
          - elk-kibana

networks:
  elk-network:
    external: true
