apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
  labels:
    app: ${SERVICE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
        - image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          name: ${SERVICE}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  ports:
    - name: pod-port
      protocol: 'TCP'
      port: 6379
      targetPort: 6379
  selector:
    app: ${SERVICE}
