version: "3"

services:
  elk-logstash:
    build: logstash/
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      elk-network:
        aliases:
          - elk-logstash

networks:
  elk-network:
    external: true
