version: '3'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80:80
      - 9113:9113
    deploy:
      replicas: 2
    networks:
      demo-network:
        aliases:
          - demo-proxy-swarm
      monitoring-network:
        aliases:
          - demo-proxy-swarm

networks:
  demo-network:
    external: true
  monitoring-network:
    external: true
