version: "3.7"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    networks:
      demo-network:
        aliases:
          - demo-web-vue

networks:
  demo-network:
    external: true
