version: '3.7'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    networks:
      staging-demo-network:
        aliases:
          - demo-web-vue

networks:
  staging-demo-network:
    external: true
